version: "3.5"

services:
  vpn:
    cap_add:
      - NET_ADMIN
    privileged: true
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./openvpn-data:/etc/openvpn
